#! /bin/sh
#-----------------------------------------------------------------------------
#   gensubst			- Generate substitutions
#
#   Copyright (C) 2013-2016 Das Computerlabor (DCl-M)
#
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Lesser General Public License
#   as published by the Free Software Foundation; either
#   version 2.1 of the License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with this library; if not, write to the Free Software Founda-
#   tion, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
#   AUTHOR(S):	ks	Karl Schmitz <ks@computerlabor.org>
#
#   WRITTEN BY:	ks	2013-02-12
#   CHANGED BY:	ks	2013-03-09	Move script comment stripping to
#					`auto/gensubst.sed'.
#		ks	2013-04-17	Fix and optimize template extraction.
#					Allow to tune the finishing mechanism
#					with $(FINISH_ANTE/POST_SEDFLAGS).
#		ks	2016-05-27	Rename $name to $subst.
#-----------------------------------------------------------------------------
#   Initialization:
#-----------------------------------------------------------------------------
LC_ALL=C; export LC_ALL			# Avoid locale insanities.

cs_upper=ABCDEFGHIJKLMNOPQRSTUVWXYZ	# Construct upper/lower-case letter,
cs_lower=abcdefghijklmnopqrstuvwxyz	# decimal digit, letter, and alpha-
cs_digit=0123456789			# numeric character sets.
cs_alpha=$cs_upper$cs_lower
cs_alnum=$cs_alpha$cs_digit

re_ident="[_$cs_alpha][_$cs_alnum]*"
re_tlead=@
re_ttail=@
rs_slead='$('
rs_stail=')'

#-----------------------------------------------------------------------------
#   Generate output variable:
#-----------------------------------------------------------------------------
if test $# -gt 0; then			# SUBSTitution given?
    subst=$1; shift			# Yes, fetch it.
    case $subst in			# Is it valid?
	CONFIG_STATUS_DEPENDENCIES|FINISH)
	    ;;
	*)  echo "$0 $subst: unknown SUBSTitution!" >&2
	    subst=usage			# No, complain and finally show
	    ;;				# usage.
    esac
else					# No substitution given.
    echo "$0: need SUBSTitution!" >&2
    subst=usage				# Complain and finally show usage.
fi

case $subst in				# Which substitution?
    CONFIG_STATUS_DEPENDENCIES|FINISH)	# Needs 'UNFINISHED ...'...
	test $# -gt 0 || {
	    echo "$0 $subst: need UNFINISHEDs!" >&2
	    subst=usage
	}
	;;
esac

case $subst in				# Which substitution?
    CONFIG_STATUS_DEPENDENCIES)
	rs_top_srcdir="${rs_slead}top_srcdir${rs_stail}"
	echo " $*" | sed 's| | '"$rs_top_srcdir"'/|g;s|^ ||'
	;;
    FINISH)
	srcdir=`dirname "$0"`		# Auto-locate (top_)srcdir...
	until test -f "$srcdir"/configure.ac; do
	    srcdir=`dirname "$srcdir"`
	done
	unfinished=`echo " $*" | sed 's| | '"$srcdir"'/|g;s|^ ||'`
	templates="`sed '
	    :1
	    /^[^'"$re_tlead"']*'"$re_tlead"'/!d;s///
	    /^'"$re_ident$re_ttail"'/{
		h;s///;x;s/'"$re_ttail"'.*$//p;x
	    };b1
	' $unfinished`" || {
	    echo "$0 $subst: Update AF_FINISH_FILES() invocation!" >&2
	    echo false
	    exit 2
	}
	if test -n "$templates"; then
	    rs_ante="${rs_slead}FINISH_ANTE_SEDFLAGS${rs_stail} -f $0.sed -e '"
	    rs_post="' ${rs_slead}FINISH_POST_SEDFLAGS${rs_stail}"
	    echo "$templates" | sort | uniq | sed '
		s/^\(.*\)$/s|'"$re_tlead"'\1'"$re_ttail"'|'"$rs_slead"'\1'"$rs_stail"'|g/
		H;$!d
		x;s|\n|;|g;s|^;||;s|^|sed '"$rs_ante"'|;s|$|'"$rs_post"'|
	    '
	else
	    echo "$0 $subst: No templates found. Do you still need me?" >&2
	    echo cat
	fi
	;;
    usage)
	echo "Usage: $0 SUBST UNFINISHED ..." >&2
	exit 2
	;;
esac
