#! /bin/sh
#-----------------------------------------------------------------------------
#   gensubst			- Generate substitutions
#
#   Copyright (C) 2013-2016 Das Computerlabor (DCl-M)
#
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Lesser General Public License
#   as published by the Free Software Foundation; either
#   version 2.1 of the License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with this library; if not, write to the Free Software Founda-
#   tion, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
#   AUTHOR(S):	ks	Karl Schmitz <ks@computerlabor.org>
#
#   WRITTEN BY:	ks	2013-02-12
#   CHANGED BY:	ks	2013-03-09	Move script comment stripping to
#					`auto/gensubst.sed'.
#		ks	2013-04-17	Fix and optimize template extraction.
#					Allow to tune the finishing mechanism
#					with $(FINISH_ANTE/POST_SEDFLAGS).
#		ks	2016-05-27	Add 'pathname' substitution.
#					Use "pathname prefix='$(srcdir)/'"
#					substitution instead of 'CONFIG_STA-
#					TUS_DEPENDENCIES' substitution.
#		ks	2016-05-28	Divide processing into phases.
#					Split 'pathname' substitution in two
#					phases.
#-----------------------------------------------------------------------------
#   Initialization:
#-----------------------------------------------------------------------------
LC_ALL=C; export LC_ALL			# Avoid locale insanities.

cs_upper=ABCDEFGHIJKLMNOPQRSTUVWXYZ	# Construct upper/lower-case letter,
cs_lower=abcdefghijklmnopqrstuvwxyz	# decimal digit, letter, and alpha-
cs_digit=0123456789			# numeric character sets.
cs_alpha=$cs_upper$cs_lower
cs_alnum=$cs_alpha$cs_digit

re_ident="[_$cs_alpha][_$cs_alnum]*"	# (Pre-)define REs for identifiers and
re_tlead=@				# templates' lead/tail.
re_ttail=@
rs_slead='$('				# (Pre-)define RE substitutions for
rs_stail=')'				# substitutions' lead/tail.

ex_vn='_\('"$re_ident"'\)='		# Define expr(1) REs for splitting
ex_vv='[^=]*=\(.*\)$'			# NAME=VALUE into NAME and VALUE.

BS=\\ SQ=\' NL='
'
sx_quote_rs='s/[\&/]/'"$BS$BS"'&/g'	# Define sed(1) script for quoting
					# RE substitutions.

#-----------------------------------------------------------------------------
#   Phase 1: Check if SUBSTitution is specified and valid
#-----------------------------------------------------------------------------
if test $# -gt 0; then			# SUBSTitution specified?
    subst=$1; shift			# Yes, fetch it.
    case $subst in			# Is it valid?
	pathname|FINISH)
	    vns=-			# Yes, start with empty NAME list.
	    ;;
	*)  echo "$0 $subst: unknown SUBSTitution!" >&2
	    subst=usage			# No, complain and finally show
	    ;;				# usage.
    esac
else					# No substitution given.
    echo "$0: need SUBSTitution!" >&2
    subst=usage				# Complain and finally show usage.
fi

#-----------------------------------------------------------------------------
#   Phase 2: Process 'NAME=VALUE' parameters
#-----------------------------------------------------------------------------
while test $# -gt 0; do
    case $1 in
	*=*)				# Looking at 'NAME=VALUE'?
	    if vn=`expr "_$1" : "$ex_vn"`; then
					# Yes, and NAME is an identifier?
		vv=`expr "$1" : "$ex_vv"`
		eval "_$vn"'=$vv'; vns=$vns$vn-
					# Yes, get VALUE and set variable.
	    else
		echo "$0 $subst $1: malformed NAME=VALUE!" >&2
		subst=usage; break	# No, complain and finally show
	    fi				# usage.
	    ;;
	*)  break			# No, assume it's an UNFINISHED.
	    ;;
    esac; shift
done

case $subst in				# Which substitution?
    FINISH)				# Needs 'UNFINISHED ...'...
	test $# -gt 0 || {
	    echo "$0 $subst: need UNFINISHEDs!" >&2
	    subst=usage
	}
	;;
esac

#-----------------------------------------------------------------------------
#   Phase 3: Apply 'prefix=PREFIX' and/or 'suffix=SUFFIX' to UNFINISHEDs
#-----------------------------------------------------------------------------
case $subst in				# Which substitution?
    pathname)				# Needs prefix/suffix applied...
	case $# in			# UNFINISHEDs specified?
	    0)	;;			# No, we're already done.
	    *)  sx='s/$/ /;'		# Yes, start out sed(1) script.
		case $vns in		# 'suffix=SUFFIX' specified?
		    *-suffix-*)		# Yes, does it apply?
			case $_suffix in
			    ?*)	rs=`sed "$sx_quote_rs" <<EOF
$_suffix
EOF`;				sx="$sx"'s/ /'"$rs"' /g;'
				;;	# Yes, augment sed(1) script so that
			esac		# UNFINISHEDs will (also) be suffixed.
			;;
		esac
		sx="$sx"'s/ $//;s/^/ /;'
		case $vns in		# 'prefix=PREFIX' specified?
		    *-prefix-*)		# Yes, does it apply?
			case $_prefix in
			    ?*)	rs=`sed "$sx_quote_rs" <<EOF
$_prefix
EOF`;				sx="$sx"'s/ / '"$rs"'/g;'
				;;	# Yes, augment sed(1) script so that
			esac		# UNFINISHEDs will be prefixed.
			;;
		esac
		sx="$sx"':1'"$NL"'s/\([ /]\)\.\//\1/;t1'"$NL"':2'"$NL"
		sx="$sx"'s/\( \.\.\/\(\.\.\/\)*\([^/ ][^/ ]*\/\)*\)[^./ ][^/ ]*\/\.\.\//\1/;t2'"$NL"
		sx="$sx"'s/\( \.\.\/\(\.\.\/\)*\([^/ ][^/ ]*\/\)*\)\.[^./ ][^/ ]*\/\.\.\//\1/;t2'"$NL"
		sx="$sx"'s/^ //'
		set shiftee `echo $* | sed "$sx"`; shift
		;;			# Yes, rewrite UNFINISHEDs.
	esac
	;;
esac

#-----------------------------------------------------------------------------
#   Phase 4: Generate substitution
#-----------------------------------------------------------------------------
case $subst in				# Which substitution?
    pathname)				# 'pathname'...
	echo ${1+"$@"}			# Emit rewritten UNFINISHEDs.
	;;
    FINISH)
	srcdir=`dirname "$0"`		# Auto-locate (top_)srcdir...
	until test -f "$srcdir"/configure.ac; do
	    srcdir=`dirname "$srcdir"`
	done
	unfinished=`echo " $*" | sed 's| | '"$srcdir"'/|g;s|^ ||'`
	templates="`sed '
	    :1
	    /^[^'"$re_tlead"']*'"$re_tlead"'/!d;s///
	    /^'"$re_ident$re_ttail"'/{
		h;s///;x;s/'"$re_ttail"'.*$//p;x
	    };b1
	' $unfinished`" || {
	    echo "$0 $subst: Update AF_FINISH_FILES() invocation!" >&2
	    echo false
	    exit 2
	}
	if test -n "$templates"; then
	    rs_ante="${rs_slead}FINISH_ANTE_SEDFLAGS${rs_stail} -f $0.sed -e '"
	    rs_post="' ${rs_slead}FINISH_POST_SEDFLAGS${rs_stail}"
	    echo "$templates" | sort | uniq | sed '
		s/^\(.*\)$/s|'"$re_tlead"'\1'"$re_ttail"'|'"$rs_slead"'\1'"$rs_stail"'|g/
		H;$!d
		x;s|\n|;|g;s|^;||;s|^|sed '"$rs_ante"'|;s|$|'"$rs_post"'|
	    '
	else
	    echo "$0 $subst: No templates found. Do you still need me?" >&2
	    echo cat
	fi
	;;
    usage)
	echo "Usage: $0 SUBST [NAME=VALUE ...] UNFINISHED ..." >&2
	exit 2
	;;
esac
